CREATE TABLE Users
(
    user_id  NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE Roles
(
    role_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY (role_id)
);

CREATE TABLE Permissions
(
    permission_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    permission_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY (permission_id)
);

CREATE TABLE UserRoles
(
    user_id NUMBER,
    role_id NUMBER,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES Users (user_id),
    FOREIGN KEY (role_id) REFERENCES Roles (role_id)
);

CREATE TABLE RolePermissions
(
    role_id       NUMBER,
    permission_id NUMBER,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES Roles (role_id),
    FOREIGN KEY (permission_id) REFERENCES Permissions (permission_id)
);

CREATE TABLE Students
(
    student_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_name VARCHAR2(50) NOT NULL,
    PRIMARY KEY (student_id)
);

CREATE TABLE Attendance
(
    attendance_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_id    NUMBER NOT NULL,
    user_id       NUMBER NOT NULL,
    date_attended DATE   NOT NULL,
    status        VARCHAR2(10) NOT NULL,
    PRIMARY KEY (attendance_id),
    FOREIGN KEY (student_id) REFERENCES Students (student_id),
    FOREIGN KEY (user_id) REFERENCES Users (user_id)
);

-- Thêm các quyền vào bảng Permissions
INSERT INTO Permissions (permission_name) VALUES ('FULL_ACCESS');
INSERT INTO Permissions (permission_name) VALUES ('VIEW_STUDENTS');
INSERT INTO Permissions (permission_name) VALUES ('VIEW_ATTENDANCE');
INSERT INTO Permissions (permission_name) VALUES ('MARK_ATTENDANCE');

-- Gán quyền cho các vai trò
-- Giảng viên A có full quyền
INSERT INTO Roles (role_name) VALUES ('GiangVienA');
INSERT INTO RolePermissions (role_id, permission_id) VALUES (1, 1); -- FULL_ACCESS

-- Giảng viên B có quyền xem danh sách học viên và điểm danh
INSERT INTO Roles (role_name) VALUES ('GiangVienB');
INSERT INTO RolePermissions (role_id, permission_id) VALUES (2, 2); -- VIEW_STUDENTS
INSERT INTO RolePermissions (role_id, permission_id) VALUES (2, 3); -- VIEW_ATTENDANCE

-- Trợ giảng X có quyền điểm danh
INSERT INTO Roles (role_name) VALUES ('TroGiangX');
INSERT INTO RolePermissions (role_id, permission_id) VALUES (3, 4); -- MARK_ATTENDANCE

-- Trợ giảng Y có quyền như Giảng viên B
INSERT INTO Roles (role_name) VALUES ('TroGiangY');
INSERT INTO RolePermissions (role_id, permission_id) VALUES (4, 2); -- VIEW_STUDENTS
INSERT INTO RolePermissions (role_id, permission_id) VALUES (4, 3); -- VIEW_ATTENDANCE